# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
    - GO111MODULE=on

before:
    hooks:
        # You may remove this if you don't use go modules.
        - go mod download
        # you may remove this if you don't need go generate
        - go generate ./...
        - ./bin/completion
        - ./bin/manpages
builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - "386"
          - amd64
          - arm
          - arm64
          - ppc64
      mod_timestamp: "{{ .CommitTimestamp }}"
      ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=source
archives:
    - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      format_overrides:
          - goos: windows
            format: zip

brews:
    - repository:
          owner: tomba-io
          name: homebrew-tap
      goarm: "7"
      homepage: https://tomba.io
      description: CLI utility to search or verify lists of email addresses in minutes.
      license: Apache-2.0
      test: |
          system "#{bin}/tomba version"
      dependencies:
          - name: go
            type: optional
          - name: git
      install: |-
          bin.install "tomba"
      extra_install: |-
          bash_completion.install "./res/package/completion/tomba.bash" => "tomba"
          zsh_completion.install "./res/package/completion/tomba.zsh" => "_tomba"
          fish_completion.install "./res/package/completion/tomba.fish"
          man1.install "./res/package/manpages/tomba.1.gz"

scoops:
    - repository:
          owner: tomba-io
          name: scoop-bucket
      homepage: https://tomba.io
      description: CLI utility to search or verify lists of email addresses in seconds.
      license: Apache-2.0

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
    name_template: "{{ .Tag }}-next"
nfpms:
    - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      homepage: https://tomba.io
      description: CLI utility to search or verify lists of email addresses in seconds.
      maintainer: Mohamed Ben rebia <b.mohamed@tomba.io>
      license: Apache-2.0
      vendor: Tomba
      section: utils
      formats:
          - apk
          - deb
          - rpm
          - archlinux
      dependencies:
          - git
          - systemd
      recommends:
          - golang
      bindir: /usr/bin
      contents:
          - src: ./res/package/system/tomba.service
            dst: /lib/systemd/system/tomba.service
          - src: ./res/package/completion/tomba.bash
            dst: /usr/share/bash-completion/completions/tomba
            file_info:
                mode: 0644
          - src: ./res/package/completion/tomba.fish
            dst: /usr/share/fish/vendor_completions.d/tomba.fish
            file_info:
                mode: 0644
          - src: ./res/package/completion/tomba.zsh
            dst: /usr/share/zsh/vendor-completions/_tomba
            file_info:
                mode: 0644
          - src: ./res/package/manpages/tomba.1.gz
            dst: /usr/share/man/man1/tomba.1.gz
            file_info:
                mode: 0644
          - src: ./LICENSE
            dst: /usr/share/doc/tomba/copyright
            file_info:
                mode: 0644
      scripts:
          postinstall: ./res/package/scripts/postinstall.sh
      rpm:
          signature:
              key_file: /tmp/signing-key.gpg
      deb:
          signature:
              key_file: /tmp/signing-key.gpg
              type: origin

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - Merge pull request
            - Merge branch
