openapi: 3.0.1
info:
    title: Tomba
    description: Find email addresses in seconds with tomba email finder
    termsOfService: https://tomba.io/privacy-policy
    contact:
        name: Tomba technology web service LLC
        url: https://tomba.io
        email: info@tomba.io
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    version: 0.0.1
externalDocs:
    description: Developers - Full API docs
    url: https://developer.tomba.io/
servers:
    - url: https://yourdomain.com
paths:
    /search:
        post:
            tags:
                - Domain
            summary: Domain Search
            description:
                "You can use this endpoint to show different browser icons to your\
                \ users. The code argument receives the browser code as it appears in your\
                \ user /account/sessions endpoint. Use width, height and quality arguments\
                \ to change the output settings."
            operationId: DomainSearch
            parameters:
                - name: domain
                  in: query
                  description:
                      "Domain name from which you want to find the email addresses.\
                      \ For example, \"stripe.com\""
                  required: true
                  schema:
                      type: string
                  example: stripe.com
                - name: page
                  in: query
                  description:
                      Specifies the number of email addresses to skip. The default
                      is 1.
                  schema:
                      type: integer
                      format: int32
                      default: 1
                  example: 10
                - name: limit
                  in: query
                  description: "Specifies the max number of email addresses to return. "
                  schema:
                      type: integer
                      format: int32
                      default: 10
                  example: 20
                - name: department
                  in: query
                  description: Get only email addresses for people working in the selected department(s).
                  schema:
                      type: string
                      enum:
                          - ""
                          - engineering
                          - sales
                          - finance
                          - hr
                          - it
                          - marketing
                          - operations
                          - management
                          - executive
                          - legal
                          - support
                          - communication
                          - software
                          - security
                          - pr
                          - warehouse
                          - diversity
                          - administrative
                          - facilities
                          - accounting
                  example: pr
            responses:
                "200":
                    description: a pet to be returned
    /author:
        post:
            tags:
                - Finder
            summary: Author Finder
            description:
                This API endpoint generates or retrieves the most likely email
                address from a blog post url.
            operationId: AuthorFinder
            parameters:
                - name: url
                  in: query
                  description:
                      "The URL of the article. For example, \"https://clearbit.com/blog/company-name-to-domain-api\"\
                      ."
                  required: true
                  schema:
                      type: string
                  example: https://clearbit.com/blog/company-name-to-domain-api
            responses:
                "200":
                    description: a pet to be returned
    /linkedin:
        post:
            tags:
                - Finder
            summary: Linkedin Finder
            description:
                This API endpoint generates or retrieves the most likely email
                address from a Linkedin URL.
            operationId: LinkedinFinder
            parameters:
                - name: url
                  in: query
                  description:
                      "The URL of the Linkedin. For example, \"https://www.linkedin.com/in/alex-maccaw-ab592978\"\
                      ."
                  required: true
                  schema:
                      type: string
                  example: https://www.linkedin.com/in/alex-maccaw-ab592978
            responses:
                "200":
                    description: a pet to be returned
    /verify:
        post:
            tags:
                - Verifier
            summary: Email Verifier
            description: verify the deliverability of an email address.
            operationId: EmailVerifier
            parameters:
                - name: email
                  in: query
                  description: The email address you want to verify.
                  required: true
                  schema:
                      type: string
                  example: b.mohamed@tomba.io
            responses:
                "200":
                    description: a pet to be returned
    /enrich:
        post:
            tags:
                - Enrichment
            summary: Enrichment
            description: The Enrichment API lets you look up person and company data based on an email
            operationId: Enrichment
            parameters:
                - name: email
                  in: query
                  description: The email address you want enrich.
                  required: true
                  schema:
                      type: string
                  example: b.mohamed@tomba.io
            responses:
                "200":
                    description: a pet to be returned
    /post:
        get:
            tags:
                - Count
            summary: get Email Count
            description: Domain name from which you want to find the email addresses.
            operationId: EmailCount
            parameters:
                - name: domain
                  in: query
                  description: The email address you want to find sources.
                  required: true
                  schema:
                      type: string
                  example: tomba.io
            responses:
                "200":
                    description: a pet to be returned
