name: Golang Build Private Tomba cli
on:
    push:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.20
              uses: actions/setup-go@v4

            - name: Check out code into the Go module directory
              uses: actions/checkout@v3

            - name: Get dependencies
              run: make deps
            - name: Build
              run: make build
