name: Goreleaser build and publish

on:
    push:
        tags:
            - "v*"
    pull_request:

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v4

            - name: Export signing key
              run: 'echo "${{ secrets.PKG_SIGNING_KEY }}" | base64 --decode > /tmp/signing-key.gpg'

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
                  BUILD_USER: ${{ github.actor }} (via Github Actions)
